[tasks.clean]
command = "rm"
args = ["-f", "image.ppm"]

[tasks.run]
script = [
	"RUSTFLAGS=\"-C target-cpu=native\" cargo run --release > image.ppm"
]

[tasks.all]
dependencies = [
	"clean",
	"run"
]